apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: backend
          image: anmaroav/ima360-golang:release-v1.0
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: "34.69.98.255"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "password"
            - name: DB_NAME
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_DRIVER
              value: "postgres"
            - name: API_SECRET
              value: "744db83c-52a1-456e-a33f-dc74358e6c65"
            - name: REFRESH_SECRET
              value: "7b0aa3b0-3f8f-49db-ac0f-19597953fbb8"
            - name: AWS_REGION
              value: "ap-southeast-1"
            - name: AWS_ACCESS_KEY_ID
              value: "AKIAJ2PR7A62UOLAAHVA"
            - name: AWS_SECRET_ACCESS_KEY
              value: "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"
            - name: BUCKET_NAME
              value: "ima-mvp-dev-bucket"
            - name: AWS_TOKEN
              value: ""
            - name: SENDGRID_API_KEY
              value: "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"
            - name: WKHTMLTOPDF_PATH
              value: "/usr/bin/wkhtmltopdf"
            - name: EMAIL_PWD
              value: "Ima@360!"
            - name: DB_HOST_ENV
              value: ""
            - name: CLOUDSQL_INSTANCE_ID
              value: ""
            - name: RELEASE_SERVER
              value: "http://34.134.26.103:3000"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
