apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: frontend
          image: anmaroav/ima360-react:latest
          env:
            - name: BASE_URL
              value: "http://35.222.155.136:8080/v1/api/"
          ports:
            - containerPort: 3000
