apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-02-14T17:08:24Z"
  generation: 1
  labels:
    app: golang
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:app: {}
          f:spec:
            f:containers:
              k:{"name":"ima360-sha256-1"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"API_SECRET"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"AWS_ACCESS_KEY_ID"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"AWS_REGION"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"AWS_SECRET_ACCESS_KEY"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"AWS_TOKEN"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"BUCKET_NAME"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"CLOUDSQL_INSTANCE_ID"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"DB_DRIVER"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"DB_HOST_ENV"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"DB_NAME"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"DB_PASSWORD"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"DB_PORT"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"DB_USER"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"EMAIL_PWD"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"GIN_MODE"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"REFRESH_SECRET"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"SENDGRID_API_KEY"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"WKHTMLTOPDF_PATH"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
    manager: GoogleCloudConsole
    operation: Update
    time: "2022-02-14T17:08:24Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:replicas: {}
        f:unavailableReplicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2022-02-14T17:09:03Z"
  name: golang
  namespace: default
  resourceVersion: "7711"
  uid: 01380e0b-aba7-4639-9816-69104a9cf33d
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: golang
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: golang
    spec:
      containers:
      - env:
        - name: GIN_MODE
          valueFrom:
            configMapKeyRef:
              key: GIN_MODE
              name: golang-config-ii7w
        - name: DB_DRIVER
          valueFrom:
            configMapKeyRef:
              key: DB_DRIVER
              name: golang-config-ii7w
        - name: API_SECRET
          valueFrom:
            configMapKeyRef:
              key: API_SECRET
              name: golang-config-ii7w
        - name: REFRESH_SECRET
          valueFrom:
            configMapKeyRef:
              key: REFRESH_SECRET
              name: golang-config-ii7w
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              key: DB_USER
              name: golang-config-ii7w
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: DB_PASSWORD
              name: golang-config-ii7w
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              key: DB_NAME
              name: golang-config-ii7w
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              key: DB_PORT
              name: golang-config-ii7w
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              key: AWS_REGION
              name: golang-config-ii7w
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            configMapKeyRef:
              key: AWS_ACCESS_KEY_ID
              name: golang-config-ii7w
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            configMapKeyRef:
              key: AWS_SECRET_ACCESS_KEY
              name: golang-config-ii7w
        - name: BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              key: BUCKET_NAME
              name: golang-config-ii7w
        - name: AWS_TOKEN
          valueFrom:
            configMapKeyRef:
              key: AWS_TOKEN
              name: golang-config-ii7w
        - name: SENDGRID_API_KEY
          valueFrom:
            configMapKeyRef:
              key: SENDGRID_API_KEY
              name: golang-config-ii7w
        - name: WKHTMLTOPDF_PATH
          valueFrom:
            configMapKeyRef:
              key: WKHTMLTOPDF_PATH
              name: golang-config-ii7w
        - name: EMAIL_PWD
          valueFrom:
            configMapKeyRef:
              key: EMAIL_PWD
              name: golang-config-ii7w
        - name: DB_HOST_ENV
          valueFrom:
            configMapKeyRef:
              key: DB_HOST_ENV
              name: golang-config-ii7w
        - name: CLOUDSQL_INSTANCE_ID
          valueFrom:
            configMapKeyRef:
              key: CLOUDSQL_INSTANCE_ID
              name: golang-config-ii7w
        image: us-central1-docker.pkg.dev/ima360/cloud-run-source-deploy/ima360@sha256:a5cf7ebaaf3cda25ab87a5c0b4238a9bc7b10f1ab67e2878cdb9daeefd577c5c
        imagePullPolicy: IfNotPresent
        name: ima360-sha256-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2022-02-14T17:08:24Z"
    lastUpdateTime: "2022-02-14T17:08:24Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2022-02-14T17:08:24Z"
    lastUpdateTime: "2022-02-14T17:09:02Z"
    message: ReplicaSet "golang-777bf45649" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 3
  unavailableReplicas: 3
  updatedReplicas: 3
